@PollDancingWebAPI_HostAddress = http://localhost:5184

GET {{PollDancingWebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{PollDancingWebAPI_HostAddress}}/senator/
Accept: application/json